from typing import Any

Client = Any

def get_client() -> Client: ...
def startUp(instance: Client, md5_token: bytes, display_name: str, user_id: str,
            engine_version: str, patch_version: str, auth_server_url: str,
            server_ip: str, netease_server_id: str, port: int) -> None: ...
def disconnect(instance: Client) -> None: ...
def delete(instance: Client) -> None: ...
