from typing import TypedDict
from api_errors import ConnectionError as ConnectionError

IMMEDIATE_PRIORITY: int
HIGH_PRIORITY: int
MEDIUM_PRIORITY: int
LOW_PRIORITY: int
UNRELIABLE: int
UNRELIABLE_SEQUENCED: int
RELIABLE: int
RELIABLE_ORDERED: int
RELIABLE_SEQUENCED: int

class ReceivedPacket(TypedDict):
    message_id: int
    payload: bytes
    address: str

class RakNet:
    def Startup(self, port: int = ..., max_connections: int = ...) -> None: ...
    def Connect(self, host: str, port: int, password: bytes = ...) -> None: ...
    def Send(self, data: bytes, priority: int = ..., reliability: int = ...,
             ordering_channel: int = ...) -> int: ...
    def Receive(self, length: int, timeout_ms: int = ...) -> bytes: ...
    def ReceivePacket(self, timeout_ms: int = ...) -> ReceivedPacket | None: ...
    def Disconnect(self) -> None: ...
    def Shutdown(self, block_duration: int = ...) -> None: ...
    def GetInstanceId(self) -> int: ...
    def GetConnectionState(self) -> int: ...
    def GetReceiveQueueSize(self) -> int: ...

def get_raknet() -> RakNet: ...
def delete(instance: RakNet) -> None: ...

