class WebSocket:
    def __init__(self, ip: str, port: int, path: str) -> None: ...
    @property
    def event_id(self) -> int: ...
    def connect(self) -> bool: ...
    def send(self, data: bytes | str) -> bool: ...
    def close(self) -> None: ...

def get_websocket(ip: str, port: int, path: str) -> WebSocket: ...
def delete(instance: WebSocket) -> None: ...
