class BotApiError(Exception): ...
class NbtError(BotApiError): ...
class PacketError(BotApiError): ...
class ConnectionError(BotApiError): ...
class CryptoError(BotApiError): ...
class ClientError(BotApiError): ...
class TimeoutError(BotApiError): ...
