def startUp(md5_token: str, display_name: str, user_id: str, engine_version: str,
            patch_version: str, auth_server_url: str, netease_server_id: str,
            server_ip: str, port: int) -> None: ...
def disconnect() -> None: ...
