def ComputeDynamicToken(token: str, body: str, url: str) -> str: ...
def HttpEncrypt(data: str) -> bytes: ...
def HttpDecrypt(data: str) -> bytes: ...
def encrypt(data: str, offset: int, rounds: int) -> bytes: ...
def Request(url: str, data: str, headers: dict[str, str]) -> bytes: ...
