from collections.abc import Callable, Sequence
from typing import Any, TypedDict

class ProtocolEvent(TypedDict):
    packet_id: int
    packet_name: str
    payload: bytes
    size: int
    parsed: bool
    data: dict[str, Any] | None
    error: str | None

def get_mcp_load_config() -> bool: ...
def rpc(data: bytes) -> None: ...
def settingscommand(command: str) -> None: ...

def register(callback: Callable[[Any], Any], event_name: str) -> None: ...
def register_kernel_event(callback: Callable[[Any], Any], event_name: str) -> None: ...
def unregister(event_name: str, callback: Callable[[Any], Any] | None = ...) -> bool: ...
def is_registered(callback: Callable[[Any], Any], event_name: str) -> bool: ...
def get_event_handler_count(event_name: str) -> int: ...
def get_events_info() -> dict[str, list[int]]: ...
def trigger(event_name: str, args: Sequence[Any] | Any = ...) -> None: ...
def get_handler_count() -> int: ...
def cleanup_all() -> None: ...
def cleanup_user() -> None: ...
def cleanup_kernel() -> None: ...

def register_protocol_event(packet_id: int, callback: Callable[[bytes], Any], is_kernel: bool) -> None: ...
def register_structured_protocol_event(packet_id: int, callback: Callable[[ProtocolEvent], Any],
                                       is_kernel: bool = ...) -> None: ...
def clear_all_protocol_event() -> None: ...
def clear_all_kernel_protocol_event() -> None: ...
def clear_all_user_protocol_event() -> None: ...

def message(sender: str, message: str) -> None: ...
def command(command: str) -> None: ...
def command_guid(command: str, guid: bytes) -> None: ...
def send(data: bytes) -> None: ...
def do_login() -> None: ...
def system(command: str) -> None: ...
def exit(code: int = ...) -> None: ...
def get_server_ip() -> str: ...
def get_server_port() -> int: ...
def get_server_sid() -> str: ...
def command_update(x: int, y: int, z: int, block_type: int, needs_redstone: bool,
                   conditional: bool, tick_delay: int, execute_on_first_tick: bool,
                   command: str, name: str) -> None: ...
def openContainer(x: int, y: int, z: int) -> dict[str, object]: ...
def getparams() -> list[str]: ...

def add_head_x(delta: float) -> None: ...
def add_head_y(delta: float) -> None: ...
def get_head_x() -> float | None: ...
def get_head_y() -> float | None: ...
def add_pot_x(delta: float) -> None: ...
def add_pot_y(delta: float) -> None: ...
def add_pot_z(delta: float) -> None: ...
def get_pot_x() -> float | None: ...
def get_pot_y() -> float | None: ...
def get_pot_z() -> float | None: ...
def move(x: float, y: float, z: float) -> None: ...
def get_subchunk_blocks(origin_x: int, origin_y: int, origin_z: int,
                        offsets: list[tuple[int, int, int]]) -> list[dict[str, object]]: ...
def get_auth_input() -> bool: ...
def disabled_auth_input() -> None: ...
def enable_auth_input() -> None: ...
def key_down(name: str) -> None: ...
def key_up(name: str) -> None: ...
def respawn() -> None: ...

def get_head_x() -> float | None: ...
def get_head_y() -> float | None: ...
def get_pot_x() -> float | None: ...
def get_pot_y() -> float | None: ...
def get_pot_z() -> float | None: ...
def get_entity_runtime_id() -> int | None: ...
