import types

def find_file(fullname: str, path: str) -> bool: ...
def get_file(fullname: str, path: str) -> bytes | None: ...
def new_module(name: str, code: types.CodeType, path: object = ...) -> types.ModuleType: ...
def new_mcp(fullname: str) -> None: ...
def reload_mcp(fullname: str) -> bool: ...
