from enum import Enum
from typing import Any, Mapping, Sequence
from api_errors import NbtError as NbtError

class TagType(Enum):
    End: TagType
    Byte: TagType
    Short: TagType
    Int: TagType
    Long: TagType
    Float: TagType
    Double: TagType
    ByteArray: TagType
    String: TagType
    List: TagType
    Compound: TagType
    IntArray: TagType
    LongArray: TagType

class Tag:
    def __init__(self) -> None: ...
    @staticmethod
    def Byte(value: int) -> Tag: ...
    @staticmethod
    def Short(value: int) -> Tag: ...
    @staticmethod
    def Int(value: int) -> Tag: ...
    @staticmethod
    def Long(value: int) -> Tag: ...
    @staticmethod
    def Float(value: float) -> Tag: ...
    @staticmethod
    def Double(value: float) -> Tag: ...
    @staticmethod
    def ByteArray(value: bytes) -> Tag: ...
    @staticmethod
    def String(value: str) -> Tag: ...
    @staticmethod
    def List(element_type: TagType, values: Sequence[Tag] = ...) -> Tag: ...
    @staticmethod
    def Compound(values: Mapping[str, Tag] = ...) -> Tag: ...
    @staticmethod
    def IntArray(value: Sequence[int]) -> Tag: ...
    @staticmethod
    def LongArray(value: Sequence[int]) -> Tag: ...
    def GetType(self) -> TagType: ...
    def GetListElementType(self) -> TagType: ...
    def GetValue(self) -> Any: ...
    def ToPython(self) -> Any: ...
    def Get(self, key_or_index: str | int) -> Tag | None: ...
    def Set(self, key: str, value: Tag) -> None: ...
    def Append(self, value: Tag) -> None: ...
    def Contains(self, key: str) -> bool: ...
    def Erase(self, key: str) -> bool: ...
    def Size(self) -> int: ...
    def ToSnbt(self) -> str: ...

class Document:
    def GetRoot(self) -> Tag: ...
    def SetRoot(self, root: Tag) -> None: ...
    def GetRootName(self) -> str: ...
    def SetRootName(self, name: str) -> None: ...
    def GetBytesRead(self) -> int: ...
    def ToSnbt(self) -> str: ...

def loads(data: bytes, encoding: str = ..., allow_trailing_data: bool = ...,
          max_depth: int = ..., max_elements: int = ...) -> Document: ...
def load_tag(data: bytes, encoding: str = ...) -> Tag: ...
def dumps(root: Tag, root_name: str = ..., encoding: str = ...) -> bytes: ...
def dump_document(document: Document, encoding: str = ...) -> bytes: ...
def flatten(tag: Tag) -> dict[str, str]: ...

