from enum import Enum
from api_errors import ConnectionError as ConnectionError, PacketError as PacketError
from typing import Any

class Packet:
    def __init__(self, packet_id: int, payload: bytes) -> None: ...
    def GetPacketID(self) -> int: ...
    def GetPacketName(self) -> str: ...
    def GetPayload(self) -> bytes: ...
    def GetData(self) -> dict[str, Any] | None: ...
    def Serialize(self) -> bytes: ...

def encode(packet_id: int, payload: bytes) -> bytes: ...
def decode(packet_id: int, payload: bytes) -> Packet: ...
def decode_bytes(data: bytes) -> Packet: ...

class CommandOrigin(Enum):
    Player: CommandOrigin
    CommandBlock: CommandOrigin
    MinecartCommandBlock: CommandOrigin
    DevConsole: CommandOrigin
    Test: CommandOrigin
    AutomationPlayer: CommandOrigin
    ClientAutomation: CommandOrigin
    DedicatedServer: CommandOrigin
    Entity: CommandOrigin
    Virtual: CommandOrigin
    GameArgument: CommandOrigin
    EntityServer: CommandOrigin
    Precompiled: CommandOrigin
    GameDirectorEntityServer: CommandOrigin
    Scripting: CommandOrigin
    ExecuteContext: CommandOrigin

class CommandRequest:
    def SetCommand(self, value: str) -> None: ...
    def GetCommand(self) -> str: ...
    def SetCommandOrigin(self, value: CommandOrigin) -> None: ...
    def GetCommandOrigin(self) -> CommandOrigin: ...
    def SetRandomUUID(self, value: bytes) -> None: ...
    def GetRandomUUID(self) -> bytes: ...
    def SetRequestID(self, value: str) -> None: ...
    def GetRequestID(self) -> str: ...
    def SetPlayerID(self, value: int) -> None: ...
    def GetPlayerID(self) -> int: ...
    def SetInternalSource(self, value: bool) -> None: ...
    def GetInternalSource(self) -> bool: ...
    def SetCommandVersion(self, value: int) -> None: ...
    def GetCommandVersion(self) -> int: ...
    def SetUnlimit(self, value: bool) -> None: ...
    def GetUnlimit(self) -> bool: ...
    def GetPacketID(self) -> int: ...
    def Serialize(self) -> bytes: ...
    def Send(self) -> int: ...
