from typing import Any, Literal, TypeVar

T = TypeVar("T")

def read_byte(data: bytes, off: int) -> tuple[int, int]: ...
def read_bool(data: bytes, off: int) -> tuple[bool, int]: ...
def read_varint(data: bytes, off: int) -> tuple[int, int]: ...
def read_svarint(data: bytes, off: int) -> tuple[int, int]: ...
def read_string(data: bytes, off: int) -> tuple[str, int]: ...
def read_u16(data: bytes, off: int) -> tuple[int, int]: ...
def read_u32(data: bytes, off: int) -> tuple[int, int]: ...
def read_i32(data: bytes, off: int) -> tuple[int, int]: ...
def read_u64(data: bytes, off: int) -> tuple[int, int]: ...
def read_i64(data: bytes, off: int) -> tuple[int, int]: ...
def read_f32(data: bytes, off: int) -> tuple[float, int]: ...
def read_f64(data: bytes, off: int) -> tuple[float, int]: ...
def read_bytes(data: bytes, off: int, count: int) -> tuple[bytes, int]: ...
def unpack(format: str, data: bytes, off: int = ...) -> tuple[Any, ...]: ...
def write_byte(value: int) -> bytes: ...
def write_bool(value: object) -> bytes: ...
def write_varint(value: int) -> bytes: ...
def write_string(value: str) -> bytes: ...
def write_u16(value: int) -> bytes: ...
def write_u32(value: int) -> bytes: ...
def write_i32(value: int) -> bytes: ...
def write_u64(value: int) -> bytes: ...
def write_f32(value: float) -> bytes: ...
def write_f64(value: float) -> bytes: ...
def pack(format: str, *values: Any) -> bytes: ...
def remaining(data: bytes, off: int) -> int: ...
