class rotor:
    def encrypt(self, data: bytes) -> bytes: ...
    def encryptmore(self, data: bytes) -> bytes: ...
    def decrypt(self, data: bytes) -> bytes: ...
    def decryptmore(self, data: bytes) -> bytes: ...
    def setkey(self, key: str) -> None: ...

def newrotor(key: str, num_rotors: int = ...) -> rotor: ...
