class TanLobbyGameCtx:
    def startUp(self, nethernet_id_to: str, nethernet_id_from: str, token: str,
                server_ip: str, server_port: int, user_id: int) -> None: ...

def create(disout: bool = ...) -> TanLobbyGameCtx: ...
