#!/usr/bin/env python3
"""从 blockStates.json 生成 C++ 方块注册表头文件(BlockRegistry.h)。

块哈希 = FNV-1a 32 over little-NBT {name, states}:
  compound(0a) + name_len(u16 LE=0) + [string 'name' + string 方块名]
  + compound 'states' + 各状态 + 00 + 00
用法: python tools/gen_block_registry.py
"""
import json
import struct
import os

SRC = os.path.join(os.path.dirname(__file__), 'data', 'blockStates_1.21.111.json')
OUT = os.path.join(os.path.dirname(__file__), '..', 'application', 'BlockRegistry.h')


def fnv1a32(s):
    h = 0x811c9dc5
    for b in s:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def u16(n):
    return struct.pack('<H', n)


def nbt_str(name, val):
    vb = val.encode('utf-8')
    return bytes([0x08]) + u16(len(name)) + name.encode() + u16(len(vb)) + vb


def nbt_comp(name, inner):
    return bytes([0x0a]) + u16(len(name)) + name.encode() + inner + b'\x00'


def nbt_byte(name, v):
    return bytes([0x01]) + u16(len(name)) + name.encode() + bytes([1 if v else 0])


def nbt_int(name, v):
    return bytes([0x03]) + u16(len(name)) + name.encode() + struct.pack('<i', v)


def state_value(raw):
    """minecraft-data states 元数据格式 {key: {type, value}} -> (type, value)"""
    if isinstance(raw, dict) and 'value' in raw:
        return raw.get('type'), raw.get('value')
    return None, raw


def block_nbt(name_with_ns, states):
    inner = b''
    for k, raw in (states or {}).items():
        stype, v = state_value(raw)
        if stype == 'string' or (stype is None and isinstance(v, str)):
            inner += nbt_str(k, v)
        elif stype == 'byte' or stype == 'bool' or (stype is None and isinstance(v, bool)):
            inner += nbt_byte(k, 1 if v else 0)   # byte/bool -> TAG_Byte(1字节)
        elif stype == 'int' or (stype is None and isinstance(v, int)):
            inner += nbt_int(k, v)
        else:
            inner += nbt_str(k, str(v))
    body = nbt_str('name', name_with_ns) + nbt_comp('states', inner)
    return bytes([0x0a]) + u16(0) + body + b'\x00'


def states_to_json(states):
    # states 为原始 {key: {type, value}} 或 {key: 值},输出紧凑 JSON(提取 value)
    parts = []
    for k, raw in (states or {}).items():
        v = raw.get('value') if isinstance(raw, dict) and 'value' in raw else raw
        if isinstance(v, str):
            parts.append('"%s":"%s"' % (k, v))
        elif isinstance(v, bool):
            parts.append('"%s":%s' % (k, 'true' if v else 'false'))
        else:
            parts.append('"%s":%d' % (k, v))
    return '{' + ','.join(parts) + '}'


def main():
    bs = json.load(open(SRC, encoding='utf-8'))
    lines = []
    lines.append('// Auto-generated by tools/gen_block_registry.py from blockStates_1.21.111.json')
    lines.append('// Block hash = FNV-1a32 over little-NBT {name, states}. Do not edit manually.')
    lines.append('#pragma once')
    lines.append('#include <cstdint>')
    lines.append('#include <cstddef>')
    lines.append('')
    lines.append('struct BlockEntry {')
    lines.append('    uint32_t hash;')
    lines.append('    const char* name;      // e.g. "minecraft:deepslate"')
    lines.append('    const char* states;    // JSON string, e.g. {"pillar_axis":"y"}')
    lines.append('};')
    lines.append('')
    lines.append('static const BlockEntry kBlockRegistry[] = {')
    all_entries = []
    for e in bs:
        nm = e['name']
        states = e.get('states') or {}   # 保留原始 {key: {type, value}} 元数据
        full = 'minecraft:' + nm
        h = fnv1a32(block_nbt(full, states))
        sj = states_to_json(states)
        c_full = full.replace('"', '\\"')
        c_sj = sj.replace('"', '\\"')
        all_entries.append((h, c_full, c_sj))
    all_entries.sort(key=lambda t: t[0])  # 按 hash 排序,支持二分查找
    for h, c_full, c_sj in all_entries:
        lines.append('    {0x%08x, "%s", "%s"},' % (h, c_full, c_sj))
    entries = len(all_entries)
    lines.append('};')
    lines.append('')
    lines.append('static const size_t kBlockRegistryCount = %d;' % entries)
    lines.append('')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('generated %d entries -> %s (%.1f KB)' % (entries, OUT, os.path.getsize(OUT) / 1024))


if __name__ == '__main__':
    main()
